### ISSUE TITLE
TFLITE Latency Problem

### ISSUE THREAD

**Issue by tulasiram58827** [tulasiram58827/craft_tflite#1] opened 2020-11-16 07:47 UTC
Although I converted craft model to tflite successfully and results seems pretty similar with the original model there are latency problems with converted tflite model.

Sample  [image](https://drive.google.com/file/d/1zfcXvRwH6OxQPjFv9V_A-XmycQg6MLx0/view?usp=sharing) used for testing.
**Before Conversion:**

1. Model Size -- 80MB
2. Time to Run -- 0.27s

**After Converting to TFLITE**

1. Model Size -- 20MB
2. Time to Run -- 25.1s

**Hardware Used:**

model name	: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz

All the models used available in the repo.

@sayakpaul

**Comment by sayakpaul** [comment] 2020-11-16 08:44
These optimizations are really targeted for a very specific set of hardware and our commodity computers don't get counted for that. 

You could use the TFLite Benchmark tool and use your Mobile Phone to see how fast it can run. Additionally, if you provide me the TFLite file I can also run it. 

Additionally, it would be great if you could add the following - 

* One liner about the CRAFT model in the README. Also, link to the CRAFT paper if possible. 
* Convert the `.py` scripts to Colab Notebooks so that they become more self-contained. 
* Add a demo inference result in the README. 

Cc: @khanhlvg FYI.

**Comment by tulasiram58827** [comment] 2020-11-16 09:28
I will update the repository with following changes.

I am new to this bench-marking tool I would request you to run it Meanwhile I will be updating the repo.

Please find the tflite file [here](https://drive.google.com/file/d/1IKNlGb0sKWxZOrOjhqhm2QESy9h0prRd/view?usp=sharing).

@sayakpaul

**Comment by sayakpaul** [comment] 2020-11-16 11:16
Great work! 

I would suggest you change the following - 

> PyTorch implementation for CRAFT text detector that effectively detect text area by exploring each character region and affinity between characters. The bounding box of texts are obtained by simply finding minimum bounding rectangles on binary map after thresholding character region and affinity scores.

to 

> The CRAFT model is a text detector that effectively detect text area by exploring each character region and affinity between characters. The bounding box of texts are obtained by simply finding minimum bounding rectangles on binary map after thresholding character region and affinity scores.

Also instead of just mentioning something like "Please find the original paper here" give the full citation - 

> The CRAFT model is proposed in this paper - [citation].

Also, separate out the Python scripts and the Colab Notebooks into folders like - `scripts` and `colabs` and then change the file descriptions accordingly. 

As for the next steps, you could write a blog post discussing the model briefly and then walking through the steps of the TFLite model conversion and inference process. Additionally, you could also include a brief comparative study between CRAFT and EAST (https://tfhub.dev/sayakpaul/lite-model/east-text-detector). I think it will make it easier for mobile application developers to choose what's best for the purpose. 

@khanhlvg would you like to share any additional thoughts? Also, should we showcase these text detectors as mobile applications?

**Comment by tulasiram58827** [comment] 2020-11-16 11:24
Sure will update. Can you share the benchmark results of tflite model.

**Comment by sayakpaul** [comment] 2020-11-16 11:38
> Can you share the benchmark results of tflite model.

Will share soon.

**Comment by sayakpaul** [comment] 2020-11-16 11:47
A couple more suggestions - 

* Please some annotations to the Notebooks along with the "Open in Colab" links. You can refer to any of the notebooks from [this repository](https://github.com/sayakpaul/Adventures-in-TensorFlow-Lite/) to get an idea of how the annotations should look like. 
* I see that you only tried the dynamic-range quantization during the TFLite conversion process. Would be interesting to see if other quantization recipes i.e. float16 and integer could also be done.

**Comment by sayakpaul** [comment] 2020-11-16 12:03
Here are the Benchmarking results - 

![image](https://user-images.githubusercontent.com/22957388/99250501-c2b3bd80-2831-11eb-8628-47d54398de9d.png)

I think the transpose operation inside the model graph is making it time-consuming.

**Comment by tulasiram58827** [comment] 2020-11-16 12:21
> A couple more suggestions -
> 
> * Please some annotations to the Notebooks along with the "Open in Colab" links. You can refer to any of the notebooks from [this repository](https://github.com/sayakpaul/Adventures-in-TensorFlow-Lite/) to get an idea of how the annotations should look like.
> * I see that you only tried the dynamic-range quantization during the TFLite conversion process. Would be interesting to see if other quantization recipes i.e. float16 and integer could also be done.

Okay will try other recipes and will add inference results.

**Comment by tulasiram58827** [comment] 2020-11-16 12:23
> Here are the Benchmarking results -
> 
> ![image](https://user-images.githubusercontent.com/22957388/99250501-c2b3bd80-2831-11eb-8628-47d54398de9d.png)
> 
> I think the transpose operation inside the model graph is making it time-consuming.

Can we modify anything to reduce latency?

**Comment by sayakpaul** [comment] 2020-11-16 12:43
I don't think so since the model has a number of transpose ops.

**Comment by tulasiram58827** [comment] 2020-11-16 13:36
Converted to TFLITE using FLOAT16 quantization and accuracy improved a lot compared to dynamic quantization although model size is increased a bit.
Attached the output in README

@sayakpaul Can you profile float 16 Quantized Model. Model is available in models folder of the repository

**Comment by sayakpaul** [comment] 2020-11-16 14:06
Yeah the model size would increase since the numerical precision is fp16 now. How about the integer quantization?

**Comment by tulasiram58827** [comment] 2020-11-16 14:18
Yeah I am in the process of doing it. It will take some time as I need to collect some data. Will update you once done.
Expect some delay

**Comment by tulasiram58827** [comment] 2020-11-17 07:28
Added Integer Quantized Model in` models` folder. Also added inferred image in README.

It would be helpful if you can add benchmarks of both float16 and integer quantized models also.

@sayakpaul

**Comment by sayakpaul** [comment] 2020-11-17 08:35
Yeah will do so.

**Comment by sayakpaul** [comment] 2020-11-17 14:51
@khanhlvg are you able to run benchmark on the following models? 

* https://storage.googleapis.com/demo-experiments/craft_float16.tflite
* https://storage.googleapis.com/demo-experiments/craft_int.tflite

I ran into the following problem when running the integer model - 

> tensorflow/lite/kernels/pad.cc:118 op_context.input->type != op_context.constant_values->type (INT8 != FLOAT32)

The float model's run became inconclusive (tried for five-six times).

**Comment by khanhlvg** [comment] 2020-11-18 00:43
@sayakpaul Could you put together a notebook that does these things?

* Use tf-nightly
* Convert the SavedModel to TFLite with multiple quantization scheme
* Feed a sample data and verify that TFLite inference work well in Colab

> tensorflow/lite/kernels/pad.cc:118 op_context.input->type != op_context.constant_values->type (INT8 != FLOAT32)

This looks like a bug that might have been fixed in tf-nightly.

> The float model's run became inconclusive (tried for five-six times).

When I tried running benchmark on my phone, it crashed the phone. I think the model input size is too large (1280x800). Could you try creating a model with smaller input size (e.g. 320 x 200)?

**Comment by sayakpaul** [comment] 2020-11-18 01:21
@tulasiram58827 over to you for addressing the above feedback. 

@khanhlvg Tulasi actually worked on these models.

**Comment by sayakpaul** [comment] 2020-11-18 01:57
@tulasiram58827 you can follow [this tutorial](https://medium.com/google-developer-experts/selfie2anime-with-tflite-part-2-tflite-model-84002cf521dc) to get an idea about how to resize the input shape of a concrete function during the model conversion step.

**Comment by tulasiram58827** [comment] 2020-11-18 02:41
Sure @sayakpaul @khanhlvg Will update and let you know

**Comment by tulasiram58827** [comment] 2020-11-18 03:32
@sayakpaul  Trying to convert using tf-nightly but faced this error.

> /home/ram/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3343:0: note: called from
/home/ram/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3263:0: note: called from
/home/ram/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071:0: note: called from
/home/ram/anaconda3/lib/python3.8/site-packages/IPython/core/async_helpers.py:68:0: note: called from
/home/ram/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:2895:0: note: called from
/home/ram/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:2866:0: note: called from
/home/ram/anaconda3/lib/python3.8/site-packages/ipykernel/zmqshell.py:536:0: note: called from
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.MaxPool {data_format = "NCHW", device = "", explicit_paddings = [], ksize = [1, 1, 2, 2], padding = "VALID", strides = [1, 1, 2, 2]}
	tf.MaxPool {data_format = "NCHW", device = "", explicit_paddings = [], ksize = [1, 1, 3, 3], padding = "VALID", strides = [1, 1, 1, 1]}

Please refer this [notebook](https://colab.research.google.com/github/tulasiram58827/craft_tflite/blob/main/colabs/savedmodel_to_tflite.ipynb) to review the step by step procedure and you can also find the full error log in the [notebook](https://colab.research.google.com/github/tulasiram58827/craft_tflite/blob/main/colabs/savedmodel_to_tflite.ipynb) itself.

**Comment by sayakpaul** [comment] 2020-11-18 03:53
I don't see the `.onnx` file inside - https://github.com/tulasiram58827/craft_tflite/tree/main/models. 

Additionally, please create notebooks such that they are runnable on Colab entirely. The notebooks should not be just uploads, which seems to be the case here. 

Also, you can try specifying the batch size to 1 instead of `None` - `concrete_func.inputs[0].set_shape([1, 3, 320, 200])`.

**Comment by tulasiram58827** [comment] 2020-11-18 04:34
Sorry for missing onnx file. Added to the `models` folder.

Updated 'savedmodel_to_tflite.ipynb` notebook and now it is runnable on Colab entirely.

Tried specifying batch size 1 still same issue.

**Comment by sayakpaul** [comment] 2020-11-18 04:37
So, the problem starts to show up when you prefix the input size, right?

**Comment by tulasiram58827** [comment] 2020-11-18 04:44
No problem started after using tf-nightly instead of tensorflow-2.3

**Comment by sayakpaul** [comment] 2020-11-18 04:55
So, when you use TensorFlow 2.3 as well as resize the inputs during conversion there are no problems, correct? 

@khanhlvg, Tulasi tried the conversion with `tf-nightly` but is running into errors (refer [here](https://github.com/tulasiram58827/craft_tflite/issues/1#issuecomment-729364767)). Here's the [Notebook](https://colab.research.google.com/github/tulasiram58827/craft_tflite/blob/main/colabs/savedmodel_to_tflite.ipynb).

**Comment by tulasiram58827** [comment] 2020-11-18 05:02
Yes.

**Comment by khanhlvg** [comment] 2020-11-18 06:09
@tulasiram58827 Thanks for the notebook. It looks like the conversion worked in TF 2.3 but failed in tf-nightly. I've reported the issue as a possible regression to TFLite Eng team.

Meanwhile, I tried conversion with dynamic range and float16, using TF 2.3 and your notebook. The model seems to work fine with the latest benchmark tool from [here](https://www.tensorflow.org/lite/performance/measurement#native_benchmark_binary).

Regarding the input size, do you know what's the size of the input image that the original model was trained with? That will be the optimal input shape for the TFLite model.

**Comment by sayakpaul** [comment] 2020-11-18 06:28
@khanhlvg thanks for the inputs. 

@tulasiram58827 could you report the benchmark results with **_4 threads_**? The instructions are available in the link Khanh provided. Of course, if you run into problems, let us know. 

@khanhlvg additionally, this project can lead to two immediate blog posts - 

* And end to end tutorial on how to convert a complex PyTorch model to TFLite. 
* Comparative study between the [EAST model](https://github.com/ml-gde/e2e-tflite-tutorials/issues/14) we had worked on earlier this year and this one (CRAFT). I think it will be incredibly helpful for many developers since text detection is a pretty useful use-case. 

Let us know your thoughts on publishing the CRAFT model on TF Hub as well (another potential byproduct of the project :)). 

Additionally, do you think a sample mobile application would be useful to demonstrate text detection?

**Comment by khanhlvg** [comment] 2020-11-18 06:31
@sayakpaul Your suggestions all sound good to me. Let's proceed!

There's only one caveat that publishing this topics to the TF Blog is likely difficult, so we'll need to find a community channel.

**Comment by tulasiram58827** [comment] 2020-11-18 06:57
> @tulasiram58827 Thanks for the notebook. It looks like the conversion worked in TF 2.3 but failed in tf-nightly. I've reported the issue as a possible regression to TFLite Eng team.
> 
> Meanwhile, I tried conversion with dynamic range and float16, using TF 2.3 and your notebook. The model seems to work fine with the latest benchmark tool from [here](https://www.tensorflow.org/lite/performance/measurement#native_benchmark_binary).
> 
> Regarding the input size, do you know what's the size of the input image that the original model was trained with? That will be the optimal input shape for the TFLite model.

Regarding the input size, I think the model is not trained with fixed size input , for each batch inputs are padded according to bigger image in the batch and trained.

**Comment by tulasiram58827** [comment] 2020-11-18 06:58
> @khanhlvg thanks for the inputs.
> 
> @tulasiram58827 could you report the benchmark results with **_4 threads_**? The instructions are available in the link Khanh provided. Of course, if you run into problems, let us know.
> 
> @khanhlvg additionally, this project can lead to two immediate blog posts -
> 
> * And end to end tutorial on how to convert a complex PyTorch model to TFLite.
> * Comparative study between the [EAST model](https://github.com/ml-gde/e2e-tflite-tutorials/issues/14) we had worked on earlier this year and this one (CRAFT). I think it will be incredibly helpful for many developers since text detection is a pretty useful use-case.
> 
> Let us know your thoughts on publishing the CRAFT model on TF Hub as well (another potential byproduct of the project :)).
> 
> Additionally, do you think a sample mobile application would be useful to demonstrate text detection?

Sure @sayakpaul will report the benchmarks with 4threads.

**Comment by khanhlvg** [comment] 2020-11-18 07:07
> Additionally, do you think a sample mobile application would be useful to demonstrate text detection?

Yes, that's will be great :)

**Comment by sayakpaul** [comment] 2020-11-18 07:21
@khanhlvg yes, I don't expect to publish any blog posts from the official TF blog because of the recent policies. Regarding the mobile application, I will send an email to our working group after we are done with the above-mentioned steps. 

@tulasiram58827 when you export the new models with reduced input dimensions how it's affecting the results? Are the results good enough? Also, after you are done with the benchmarking steps, you can follow the instructions [here](https://github.com/tensorflow/hub/blob/master/docs/contribute_a_model.md) to know how to publish from TensorFlow Hub. You can refer [here](https://github.com/sayakpaul/hub/tree/master/tfhub_dev/assets/sayakpaul/east-text-detector) to see how I prepared the EAST documentation. 

After this, let's start the writing process.

**Comment by tulasiram58827** [comment] 2020-11-18 13:34
@sayakpaul  Sorry for late response. With (320 * 200) they are not good enough. With (800*600) working better. Need to check with more input dimensions and images. If you can suggest any input dimensions I will try with them.

Sounds like a plan. For now I will run benchmark with (800*600) models and let you know.

**Comment by sayakpaul** [comment] 2020-11-18 13:59
I think 800x600 is good enough. 

For EAST (https://github.com/sayakpaul/Adventures-in-TensorFlow-Lite/blob/master/EAST_TFLite.ipynb) I used 320x320.

**Comment by tulasiram58827** [comment] 2020-11-18 14:48
Benchmark Results with (800*600):

1. For dynamic quantized model: (Find the model [here](https://github.com/tulasiram58827/craft_tflite/blob/main/models/craft_800.tflite))
> STARTING!
Log parameter values verbosely: [0]
Num threads: [4]
Graph: [/home/ram/Projects/OCR/craft_tflite/models/craft_800.tflite]
#threads used for CPU inference: [4]
Loaded model /home/ram/Projects/OCR/craft_tflite/models/craft_800.tflite
The input model file size (MB): 20.894
Initialized session in 13.344ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=1 curr=29409930
Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=6 first=29207301 curr=30814699 min=29207301 max=30814699 avg=2.98909e+07 std=522529
Inference timings in us: Init: 13344, First inference: 29409930, Warmup (avg): 2.94099e+07, Inference (avg): 2.98909e+07
Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
Peak memory footprint (MB): init=3.76953 overall=616.238

2. For Float 16 Quantized Models: (Find the model [here](https://github.com/tulasiram58827/craft_tflite/blob/main/models/craft_float_800.tflite))
>STARTING!
Log parameter values verbosely: [0]
Num threads: [4]
Graph: [/home/ram/Projects/OCR/craft_tflite/models/craft_float_800.tflite]
#threads used for CPU inference: [4]
Loaded model /home/ram/Projects/OCR/craft_tflite/models/craft_float_800.tflite
The input model file size (MB): 41.627
Initialized session in 18.644ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=1 curr=7922098
Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=20 first=7447210 curr=7702156 min=7359269 max=7988356 avg=7.68431e+06 std=205710
Inference timings in us: Init: 18644, First inference: 7922098, Warmup (avg): 7.9221e+06, Inference (avg): 7.68431e+06
Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
Peak memory footprint (MB): init=4.97266 overall=621.371

**Comment by tulasiram58827** [comment] 2020-11-18 15:39
@khanhlvg : When I am trying to infer from integer quantized or fully integer quantized I am getting this error.
> RuntimeError: tensorflow/lite/kernels/pad.cc:118 op_context.input->type != op_context.constant_values->type (INT8 != FLOAT32)Node number 103 (PADV2) failed to prepare.

To reproduce the error refer to this [Notebook](https://colab.research.google.com/github/tulasiram58827/craft_tflite/blob/main/colabs/savedmodel_to_tflite.ipynb). While doing inference in the notebook you can use any sample image.

**Comment by tulasiram58827** [comment] 2020-11-19 05:02
@sayakpaul  @khanhlvg  FYI 
[PR](https://github.com/tensorflow/hub/pull/702) has been created to publish craft tflite models in Tensorflow Hub [repository](https://github.com/tensorflow/hub)

**Update** : As suggested by Marin Georgiev created new [PR](https://github.com/tensorflow/tfhub.dev/pull/20) in the new [Repository](https://github.com/tensorflow/tfhub.dev)

**Comment by sayakpaul** [comment] 2020-11-19 05:41
> @khanhlvg : When I am trying to infer from integer quantized or fully integer quantized I am getting this error.
> 
> > RuntimeError: tensorflow/lite/kernels/pad.cc:118 op_context.input->type != op_context.constant_values->type (INT8 != FLOAT32)Node number 103 (PADV2) failed to prepare.
> 
> To reproduce the error refer to this [Notebook](https://colab.research.google.com/github/tulasiram58827/craft_tflite/blob/main/colabs/savedmodel_to_tflite.ipynb). While doing inference in the notebook you can use any sample image.

@tulasiram58827 what does [this quantization](https://github.com/tulasiram58827/craft_tflite#tflite-model-outputinteger-quantization) refer to then?

**Comment by tulasiram58827** [comment] 2020-11-19 05:50
It was a mistake. Updating now.

**Update** : Rolled Back

**Comment by khanhlvg** [comment] 2020-11-26 01:03
> @khanhlvg : When I am trying to infer from integer quantized or fully integer quantized I am getting this error.
> 
> > RuntimeError: tensorflow/lite/kernels/pad.cc:118 op_context.input->type != op_context.constant_values->type (INT8 != FLOAT32)Node number 103 (PADV2) failed to prepare.
> 
> To reproduce the error refer to this [Notebook](https://colab.research.google.com/github/tulasiram58827/craft_tflite/blob/main/colabs/savedmodel_to_tflite.ipynb). While doing inference in the notebook you can use any sample image.

Unfortunately support NCHW image format (like those converted from PyTorch) is quite limited at this moment, which caused this issue with full integer quantized model. We're working on improving it but I will take some time.

**Closed as completed** 2020-11-27 17:08 UTC
